name: "Название аддона"
slug: "slug_аддона"
description: "Описание"
version: "1.0.0"
arch:
  - amd64
  - armv7
  - aarch64
startup: "application"
boot: "auto"
homeassistant_api: true  # если нужен HA API
