name: "MiniDSP 2x4 HD USB"
slug: minidsp_2x4hd_usb
description: "USB control for miniDSP 2x4 HD"
version: "1.0.0"
arch:
  - aarch64
  - armv7
  - amd64
startup: "application"
boot: "auto"
map:
  - share:rw
devices:
  - /dev/hidraw*
  - /dev/bus/usb
privileged: true
homeassistant_api: true
